### PR TITLE
Safety is important part of our live

### PR DESCRIPTION
**Pull request by estin**
I don't blame rust-secure-code team about this sad story around actix.

All I want - don't growing beginners like me with one opinion about safety.
Yes `unsafe`  code can be `safe`.
And Rust app can be `safe` as you want.
But in general way rust app can be `unsafe` and it is a choice who use it.

And check the safety-dance image https://github.com/estin/safety-dance/blob/master/img/safety-dance.png

Feel free to close this emotional PR.
P.S. Sorry about my poor English.

### CODE REVIEW

**Comment by Lokathor** [comment]
Safety dance isn't about eliminating all unsafe code.

It's about auditing all unsafe code for correctness.

However, if you reduce the amount of unsafe code it obviously doesn't need to be audited any more.

That is why reducing the amount of unsafe code helps the goal of auditing. Less unsafe code means less unsafe code to audit.

**Comment by tarcieri** [comment]
re: the logo change, what it evokes for me is the safety dance crabs ganging up and encircling Actix, which I think is the opposite of what we want to convey

**Comment by tarcieri** [comment]
@estin I do appreciate the sentiment of this PR, and I hope we can learn from this incident

**Comment by estin** [comment]
It was emotions.
I hope we all become better )

**Pull request closed without merging**
